{
 "title": "HTTP/S GCP Load Balancer Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "stackdriver" },
   {
    "name": "project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/total_latencies",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/response_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Frontend RTT [95/50/5 PERCENTILE].",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "ALIGN_DELTA  REDUCE_PERCENTILE_95 {{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "ALIGN_PERCENTILE_99 REDUCE_PERCENTILE_05 {{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "ALIGN_DELTA REDUCE_PERCENTILE_50 {{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_response_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95 {{resource.label.url_map_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}